python train_graphsage.py --dataset-root produced_data/dataset0 --epochs 5
python train_graphsage.py --dataset-root produced_data/dataset1 --epochs 5
python train_graphsage.py --dataset-root produced_data/dataset2 --epochs 5
python train_graphsage.py --dataset-root produced_data/dataset3 --epochs 5
python train_graphsage.py --dataset-root produced_data/dataset4 --epochs 5
python train_graphsage.py --dataset-root produced_data/dataset5 --epochs 5
python train_graphsage.py --dataset-root produced_data/dataset6 --epochs 5
python train_graphsage.py --dataset-root produced_data/dataset7 --epochs 5
python train_graphsage.py --dataset-root produced_data/dataset8 --epochs 5
python train_graphsage.py --dataset-root produced_data/dataset9 --epochs 5
